# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
#        in_memory:
#            memory: ~
        main:
            id: fos_user.user_provider.username
#            id: AVListeVoeuBundle\Entity\Agent
            
    encoders:
#        AV\ListeVoeuBundle\Entity\Agent: sha512
        FOS\UserBundle\Model\UserInterface: plaintext

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        #~ main_index:
            #~ pattern: ^/$
            #~ anonymous: true
        main_login:
            pattern: ^/login$
            anonymous: true
        
        main:
            pattern: ^/
            anonymous: false
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path: fos_user_security_logout
                target: fos_user_security_login
                
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
