<?php

namespace AV\ListeVoeuBundle\Repository;

/**
 * DirectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DirectionRepository extends \Doctrine\ORM\EntityRepository
{
}
