<?php

namespace AV\ListeVoeuBundle\Repository;

/**
 * ResidencePosteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResidencePosteRepository extends \Doctrine\ORM\EntityRepository
{
}
