<?php

namespace AV\ListeVoeuBundle\Repository;

/**
 * VoeuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoeuRepository extends \Doctrine\ORM\EntityRepository
{
}
