accueil:
    path:     /
    defaults: {_controller: AVListeVoeuBundle:Home:index}
add_agent:
    path:     /agent/add
    defaults: {_controller: AVListeVoeuBundle:Agent:add}
edit_agent:
    path:     /agent/edit/{agent_id}
    defaults: {_controller: AVListeVoeuBundle:Agent:edit}
    requirements:
        agent_id: \d+
av_liste_agent_view:
    path:     /agent
    defaults: {_controller: AVListeVoeuBundle:Agent:index}
liste_choix:
    path:     /liste
    defaults: {_controller: AVListeVoeuBundle:Liste:index}
liste_add:
    path:     /liste/add
    defaults: {_controller: AVListeVoeuBundle:Liste:ajout}
liste_agent:
    path:     /liste/{list_id}
    defaults: {_controller: AVListeVoeuBundle:Liste:index}
    requirements:
        list_id: \d+
liste_supp:
    path:     /liste/supp/{list_id}
    defaults: {_controller: AVListeVoeuBundle:Liste:supp}
    requirements:
        list_id: \d+
fos_user_security_login:
    path: /login
    defaults: {_controller: FOSUserBundle:Security:login}

fos_user_security_check:
    path: /login_check

fos_user_security_logout:
    path: /logout
test:
    path: /test
    defaults: {_controller:AVListeVoeuBundle:Agent:test}
add_residence:
    path:     /residence/add
    defaults: {_controller: AVListeVoeuBundle:Residence:add}
del_residence:
    path:     /residence/del/{residence_id}
    defaults: {_controller: AVListeVoeuBundle:Residence:del}
    requirements:
        residence_id: \d+
edit_residence:
    path:     /residence/edit/{residence_id}
    defaults: {_controller: AVListeVoeuBundle:Residence:edit}
    requirements:
        residence_id: \d+
list_residence:
    path:     /residence
    defaults: {_controller: AVListeVoeuBundle:Residence:list}
add_residence_poste:
    path:     /residence_poste/add
    defaults: {_controller: AVListeVoeuBundle:ResidencePoste:add}
del_residence_poste:
    path:     /residence_poste/del/{residence_id}/{poste_id}
    defaults: {_controller: AVListeVoeuBundle:ResidencePoste:del}
    requirements:
        residence_id: \d+
        poste_id: \d+
list_residence_poste:
    path:     /residence_poste
    defaults: {_controller: AVListeVoeuBundle:ResidencePoste:list}
